[package]
name = "stm32f30x-hal-example"
version = "0.1.0"
authors = ["Pramode <mail@pramode.in>"]

[dependencies]
stm32f30x-hal = "0.1.2"
nb = "0.1.1"
cortex-m = "0.4.3"
cortex-m-rt = "0.3.12"
adc-mcp3008 = "0.1.1"

